controller_list:
  - name: fake_group1_controller
    type: $(arg fake_execution_type)
    joints:
      - Rev4
      - Rev5
      - Rev6
initial:  # Define initial robot poses per group
  - group: group1
    pose: pose1