group1_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - Rev4
    - Rev5
    - Rev6
  gains:
    Rev4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Rev6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1